---
# Site Settings
locale                   : "en-US"
title                    : "A sociological file"
title_separator          : "-"
name                     : "Martin Andersen"
description              : "A collection of thoughts and reflections."
url                      : https://martinadreasandersen.com/ # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : norseghost/norseghost.github.io # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
google_site_verification: "sDFCelf4cTZS9wPKmXVLT1SSr4OgwTOPnwG27nRHYog"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200

atom_feed:
  path                   : # blank (default) uses feed.xml
# Site Author
author:
  address:
    - Enggården 35 
    - 9520 Skørping
    - Danmark
  name             : "Martin Andreas Andersen"
  avatar           : "/assets/images/bio-picture.jpg"
  bio              : "Sociology student, with a background in work with adults with severe cognitive disabilities"
  location         : "Skørping, DK"
  email            : martin.andreas.andersen@gmail.com
  phone: "+45 52 39 85 86"
  uri              : 
  home             : /martin/ # null (default), "absolute or relative url to link to author home"
  bitbucket        :
  codepen          :
  facebook         : draug3n
  github           : norseghost
  gitlab           : 
  keybase          :
  instagram        : martin.andreas.andersen
  linkedin         : norseghost/
  stackoverflow    : "3973557/martin-andersen"
  steam            :
  tumblr           :
  twitter          : "norseghost"
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"
  links:
    label: "CV (English)"
    icon: "fab fa-fw fa-file-alt"
    url: "https://martinandreasandersen.com/cv-en/"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:title/
paginate: 5
paginate_path: /page:num/

# pagination:
#   enabled: true
#   per_page: 5 # amount of posts to show
#   permalink: /page/:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# theme: "minimal-mistakes-jekyll"
remote_theme                    : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jemoji
#  - jekyll-archives 

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

collections:
  guides:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: false
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: false
      related: true
  # _guides
  - scope:
      path: ""
      type: guides
    values:
      layout: single
      author_profile: true
    sidebar:
      nav: "guides"
  # _guides
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
    sidebar:
      nav: "projects"
---
